# config/packages/knp_paginator.yaml

knp_paginator:
  #    page_range: 3                       # Nombre de liens affichés dans le menu de pagination (par exemple : vous avez 10 pages, un page_range de 3, sur la 5ème page vous verrez des liens vers la page 4, 5, 6).
  default_options:
    page_name: page                 # Nom du paramètre de requête pour la page
    sort_field_name: sort           # Nom du paramètre de requête pour le champ de tri
    sort_direction_name: direction  # Nom du paramètre de requête pour la direction du tri
    distinct: true                  # Assure des résultats distincts, utile lorsque les requêtes ORM utilisent des instructions GROUP BY
    filter_field_name: filterField  # Nom du paramètre de requête pour le champ de filtre
    filter_value_name: filterValue
  template:
    pagination: '@KnpPaginator/Pagination/bootstrap_v5_pagination.html.twig'
    sortable: '@KnpPaginator/Pagination/bootstrap_v5_bi_sortable_link.html.twig'
    filtration: '@KnpPaginator/Pagination/bootstrap_v5_filtration.html.twig'